# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coder Club
email: coder@coderclub.cc
description: > # this means to ignore newlines until "baseurl:"
  Coder Club 天津最具实力的coder组织，Let`s Make Future!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://coderclub.cc" # the base hostname & protocol for your site
twitter_username: coderclub
github_username:  CoderClubcc

# Build settings
markdown: kramdown
